# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-11-30 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201130_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 10, 22, 54, 62263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 10, 22, 54, 62263, tzinfo=utc)),
        ),
    ]
