# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-12-27 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201227_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 7, 55, 58, 360881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 7, 55, 58, 359840, tzinfo=utc)),
        ),
    ]
